# Generated by Django 5.0.4 on 2024-04-20 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.URLField()),
                ('latitude', models.DecimalField(decimal_places=6, default=40.984396, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=29.025434, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('e_mail', models.EmailField(max_length=255, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('duration', models.JSONField(blank=True, default=list)),
                ('duration_between', models.JSONField(blank=True, default=list)),
                ('mapView', models.URLField()),
                ('nodes', models.ManyToManyField(related_name='routes', to='database_search.node')),
            ],
        ),
    ]
