# Generated by Django 5.0.4 on 2024-04-17 22:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Route',
            new_name='RouteObject',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserObject',
        ),
    ]
