# Generated by Django 4.2.11 on 2024-04-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0001_initial'),
    ]

    operations = [
    ]
