# Generated by Django 5.0.4 on 2024-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0002_rename_route_routeobject_rename_user_userobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photos', models.JSONField(blank=True, default=list)),
                ('rating', models.FloatField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.JSONField(blank=True, default=list)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('nodes', models.JSONField(blank=True, default=list)),
                ('duration', models.JSONField(blank=True, default=list)),
                ('duration_between', models.JSONField(blank=True, default=list)),
                ('mapView', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userobject',
            name='user',
        ),
        migrations.DeleteModel(
            name='RouteObject',
        ),
        migrations.DeleteModel(
            name='UserObject',
        ),
    ]
