# Generated by Django 5.0.4 on 2024-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0003_node_route_remove_userobject_routes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='nodes',
        ),
        migrations.AddField(
            model_name='route',
            name='nodes',
            field=models.ManyToManyField(related_name='routes', to='database_search.node'),
        ),
    ]
