# Generated by Django 5.0.4 on 2024-04-18 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0004_remove_route_nodes_route_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=40.984396, max_digits=9),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=29.025434, max_digits=9),
        ),
        migrations.AlterField(
            model_name='route',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
