# Generated by Django 4.2.13 on 2024-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0004_remove_route_nodes_route_node_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
