# Generated by Django 4.2.13 on 2024-05-14 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0006_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
