# Generated by Django 4.2.13 on 2024-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0009_remove_route_user_id_route_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='node_names',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
