version: "3"
services:
  app:
    build: ./django_project_491
    image: kayikci/app:latest
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - REACT_APP_API_URL=http://localhost:8000/
    ports:
      - "8000:8000"

  web:
    build: ./koduyorum-web
    image: kayikci/web:latest
    environment:
      - REACT_APP_API_URL=http://localhost:8000/
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - app
