# Generated by Django 4.2.11 on 2024-04-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
