# Generated by Django 5.0.4 on 2024-04-15 22:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photos', models.JSONField()),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.JSONField()),
                ('saves', models.PositiveIntegerField(default=0)),
                ('nodes', models.JSONField()),
                ('mapView', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profilePicture', models.URLField(blank=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='is_followed_by', to='database_search.user')),
                ('following', models.ManyToManyField(blank=True, related_name='is_following', to='database_search.user')),
                ('routes', models.ManyToManyField(blank=True, related_name='users_routes', to='database_search.route')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
