# Generated by Django 4.2.13 on 2024-05-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0003_remove_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='nodes',
        ),
        migrations.AddField(
            model_name='route',
            name='node_ids',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
