# Generated by Django 4.2.13 on 2024-05-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0007_alter_route_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='user',
            new_name='user_id',
        ),
    ]
