# Generated by Django 4.2.13 on 2024-05-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_search', '0008_rename_user_route_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='user_id',
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
