
export const predefinedTags = [
    // Programming Fundamentals
    'Algorithms',
    'Data Structures',
    'Recursion',
    'Dynamic Programming',
    'Object-Oriented Programming',
    'Functional Programming',
    'Memory Management',
    'Pointers',
    'Arrays',
    'Linked Lists',
    'Trees',
    'Graphs',
    'Hash Tables',
    'Stacks',
    'Queues',
    'Sorting',
    'Searching',
    'Time Complexity',
    'Space Complexity',
    'Big O Notation',

    // Software Development Concepts
    'Design Patterns',
    'SOLID Principles',
    'Clean Code',
    'Code Review',
    'Debugging',
    'Error Handling',
    'Exception Handling',
    'Logging',
    'Documentation',
    'Unit Testing',
    'Integration Testing',
    'Test-Driven Development',
    'Continuous Integration',
    'Version Control',
    'Git',
    'Code Quality',
    'Performance Optimization',
    'Refactoring',
    'Technical Debt',

    // Web Development
    'Frontend',
    'Backend',
    'Full Stack',
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Express.js',
    'REST API',
    'GraphQL',
    'WebSockets',
    'Authentication',
    'Authorization',
    'OAuth',
    'JWT',
    'Web Security',
    'CORS',
    'HTTP',
    'HTTPS',
    'SSL/TLS',
    'Responsive Design',
    'Progressive Web Apps',
    'Web Components',
    'DOM',
    'Browser APIs',
    'Web Performance',
    "Django",

    // Database & Storage
    'SQL',
    'NoSQL',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'Redis',
    'Database Design',
    'Data Modeling',
    'Indexing',
    'Query Optimization',
    'Transactions',
    'ACID',
    'Caching',
    'Data Migration',
    'Backups',
    'Data Warehousing',

    // DevOps & Infrastructure
    'DevOps',
    'CI/CD',
    'Docker',
    'Kubernetes',
    'Containerization',
    'Microservices',
    'Service Mesh',
    'Cloud Computing',
    'AWS',
    'Azure',
    'Google Cloud',
    'Serverless',
    'Infrastructure as Code',
    'Configuration Management',
    'Monitoring',
    'Logging',
    'System Design',
    'Load Balancing',
    'Scalability',
    'High Availability',

    // Programming Languages
    'Python',
    'Java',
    'C',
    'C++',
    'C#',
    'Ruby',
    'PHP',
    'Go',
    'Rust',
    'Swift',
    'Kotlin',
    'Scala',
    'R',
    'MATLAB',
    'Assembly',
    'Bash',
    'PowerShell',

    // Mobile Development
    'iOS Development',
    'Android Development',
    'React Native',
    'Flutter',
    'Mobile UI/UX',
    'App Store',
    'Google Play',
    'Mobile Security',
    'Push Notifications',
    'Mobile Performance',
    'Mobile Testing',

    // AI & Machine Learning
    'Machine Learning',
    'Deep Learning',
    'Neural Networks',
    'Computer Vision',
    'Natural Language Processing',
    'Reinforcement Learning',
    'Data Mining',
    'Feature Engineering',
    'Model Training',
    'Model Deployment',
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',

    // Security
    'Cyber Security',
    'Encryption',
    'Penetration Testing',
    'Vulnerability Assessment',
    'Network Security',
    'Application Security',
    'Security Protocols',
    'Cryptography',
    'Security Best Practices',
    'Ethical Hacking',

    // Software Architecture
    'Architecture Patterns',
    'Domain-Driven Design',
    'Event-Driven Architecture',
    'Monolithic Architecture',
    'Distributed Systems',
    'API Design',
    'System Integration',
    'Message Queues',
    'Caching Strategies',
    'Data Flow',

    // Development Methodologies
    'Agile',
    'Scrum',
    'Kanban',
    'Waterfall',
    'Lean',
    'XP',
    'Project Management',
    'Team Collaboration',
    'Code Review Process',
    'Documentation Practices',

    // Emerging Technologies
    'Blockchain',
    'IoT',
    'Edge Computing',
    'Quantum Computing',
    'AR/VR',
    '5G',
    'Web3',
    'DeFi',
    'Smart Contracts',
    'Metaverse',

    // Career & Professional Development
    'Career Development',
    'Interview Preparation',
    'Code Challenge',
    'Best Practices',
    'Soft Skills',
    'Technical Writing',
    'Public Speaking',
    'Leadership',
    'Mentoring',
    'Remote Work',

    // Tools & Development Environment
    'IDE',
    'VS Code',
    'IntelliJ',
    'Eclipse',
    'Command Line',
    'Terminal',
    'Development Tools',
    'Productivity Tools',
    'Code Editors',
    'Debugging Tools',

    // GPU & Parallel Computing
    'CUDA',
    'OpenCL',
    'GPU Programming',
    'Parallel Computing',
    'GPGPU',
    'Vulkan',
    'Metal',
    'DirectX',
    'OpenGL',
    'Shader Programming',

    // AI & ML Extensions
    'LLMs',
    'Transformers',
    'HuggingFace',
    'MLOps',
    'RAG',
    'Vector Databases',
    'Prompt Engineering',
    'ONNX',
    'JAX',
    'AutoML',

    // Cloud Native & Modern Infrastructure
    'Terraform',
    'Ansible',
    'GitOps',
    'Service Discovery',
    'gRPC',
    'Istio',
    'Helm',
    'ArgoCD',
    'Prometheus',
    'Grafana',

    // Modern Development
    'WebAssembly',
    'Rust WebAssembly',
    'Svelte',
    'Next.js',
    'Remix',
    'Tailwind CSS',
    'Vite',
    'esbuild',
    'Deno',
    'Bun',

    // Specialized Areas
    'Game Development',
    'Unity3D',
    'Unreal Engine',
    'Embedded Systems',
    'Real-time Systems',
    'Computer Graphics',
    'Audio Programming',
    'Network Programming',
    'WebRTC',
    'Web3D',

    // Computer Architecture
    'Pipeline Processing',
    'Cache Management',
    'Virtual Memory',
    'RISC',
    'CISC',
    'Branch Prediction',
    'Instruction Sets',
    'CPU Architecture',
    'Memory Hierarchy',
    'Register Allocation',

    // Low-Level Programming
    'Assembly Language',
    'Bytecode',
    'Memory Mapping',
    'Interrupt Handling',
    'DMA',
    'Device Drivers',
    'Firmware',
    'Bare Metal Programming',
    'Binary Analysis',
    'System Calls',

    // Operating Systems Concepts
    'Process Scheduling',
    'Thread Management',
    'Deadlock Prevention',
    'Synchronization Primitives',
    'File Systems',
    'I/O Management',
    'Memory Segmentation',
    'Kernel Development',
    'Boot Process',
    'Context Switching',

    // Networking & Protocols
    'Network Protocols',
    'TCP/IP Stack',
    'Socket Programming',
    'Network Drivers',
    'Packet Analysis',
    'Protocol Buffers',
    'Network Routing',
    'Load Balancers',
    'Network Security',
    'Bandwidth Optimization',

    // Advanced Programming Concepts
    'Tail Recursion',
    'Memory Pools',
    'Zero-Copy',
    'Lock-Free Programming',
    'SIMD',
    'Vectorization',
    'Cross-Compilation',
    'Static Analysis',
    'Code Generation',
    'Compiler Design',

    // Real-Time Systems
    'Real-Time Operating Systems',
    'Embedded Linux',
    'QNX',
    'FreeRTOS',
    'Hard Real-Time',
    'Soft Real-Time',
    'Rate-Monotonic Scheduling',
    'Priority Inversion',
    'Watchdog Timers',
    'Task Scheduling',

    // Hardware Design
    'FPGA Programming',
    'Verilog',
    'VHDL',
    'Digital Logic',
    'Hardware Description',
    'Circuit Design',
    'PCB Design',
    'Signal Processing',
    'Microcontroller Programming',
    'SoC Design',

    // Performance Engineering
    'Cache Optimization',
    'Memory Alignment',
    'Branch Optimization',
    'Profiling Tools',
    'Performance Monitoring',
    'Bottleneck Analysis',
    'Latency Analysis',
    'Resource Utilization',
    'Power Optimization',
    'Benchmark Development',

    // Systems Programming
    'ELF Format',
    'Linker Scripts',
    'ABI Compatibility',
    'System Bootstrapping',
    'IPC Mechanisms',
    'Memory Management Unit',
    'Page Tables',
    'Syscall Implementation',
    'Process Forking',
    'Signal Handling',

    // Fault Tolerance
    'Error Detection',
    'Fault Recovery',
    'Redundancy Systems',
    'Failover Mechanisms',
    'State Machine Design',
    'Byzantine Fault Tolerance',
    'Checkpoint Recovery',
    'Data Consistency',
    'Distributed Consensus',
    'High Availability Design'

];

export const languages = [
    "Assembly (NASM 2.14.02)",
    "Bash (5.0.0)",
    "Basic (FBC 1.07.1)",
    "C (Clang 18.1.8)",
    "C (Clang 7.0.1)",
    "C++ (Clang 7.0.1)",
    "C (GCC 14.1.0)",
    "C++ (GCC 14.1.0)",
    "C (GCC 7.4.0)",
    "C++ (GCC 7.4.0)",
    "C (GCC 8.3.0)",
    "C++ (GCC 8.3.0)",
    "C (GCC 9.2.0)",
    "C++ (GCC 9.2.0)",
    "Clojure (1.10.1)",
    "C# (Mono 6.6.0.161)",
    "COBOL (GnuCOBOL 2.2)",
    "Common Lisp (SBCL 2.0.0)",
    "Dart (2.19.2)",
    "D (DMD 2.089.1)",
    "Elixir (1.9.4)",
    "Erlang (OTP 22.2)",
    "Executable",
    "F# (.NET Core SDK 3.1.202)",
    "Fortran (GFortran 9.2.0)",
    "Go (1.13.5)",
    "Go (1.18.5)",
    "Groovy (3.0.3)",
    "Haskell (GHC 8.8.1)",
    "JavaFX (JDK 17.0.6, OpenJFX 22.0.2)",
    "Java (JDK 17.0.6)",
    "Java (OpenJDK 13.0.1)",
    "JavaScript (Node.js 12.14.0)",
    "JavaScript (Node.js 18.15.0)",
    "JavaScript (Node.js 20.17.0)",
    "JavaScript (Node.js 22.08.0)",
    "Kotlin (1.3.70)",
    "Lua (5.3.5)",
    "Multi-file program",
    "Objective-C (Clang 7.0.1)",
    "OCaml (4.09.0)",
    "Octave (5.1.0)",
    "Pascal (FPC 3.0.4)",
    "Perl (5.28.1)",
    "PHP (7.4.1)",
    "PHP (8.3.11)",
    "Plain Text",
    "Prolog (GNU Prolog 1.4.5)",
    "Python (2.7.17)",
    "Python (3.11.2)",
    "Python (3.12.5)",
    "Python (3.8.1)",
    "R (4.0.0)",
    "R (4.4.1)",
    "Ruby (2.7.0)",
    "Rust (1.40.0)",
    "Scala (2.13.2)",
    "SQL (SQLite 3.27.2)",
    "Swift (5.2.3)",
    "TypeScript (3.7.4)",
    "TypeScript (5.0.3)",
    "TypeScript (5.6.2)",
    "Visual Basic.Net (vbnc 0.0.0.5943)"
]