
export const predefinedTags = [
    // Programming Fundamentals
    'Algorithms',
    'Data Structures',
    'Recursion',
    'Dynamic Programming',
    'Object-Oriented Programming',
    'Functional Programming',
    'Memory Management',
    'Pointers',
    'Arrays',
    'Linked Lists',
    'Trees',
    'Graphs',
    'Hash Tables',
    'Stacks',
    'Queues',
    'Sorting',
    'Searching',
    'Time Complexity',
    'Space Complexity',
    'Big O Notation',

    // Software Development Concepts
    'Design Patterns',
    'SOLID Principles',
    'Clean Code',
    'Code Review',
    'Debugging',
    'Error Handling',
    'Exception Handling',
    'Logging',
    'Documentation',
    'Unit Testing',
    'Integration Testing',
    'Test-Driven Development',
    'Continuous Integration',
    'Version Control',
    'Git',
    'Code Quality',
    'Performance Optimization',
    'Refactoring',
    'Technical Debt',

    // Web Development
    'Frontend',
    'Backend',
    'Full Stack',
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'Angular',
    'Vue.js',
    'Node.js',
    'Express.js',
    'REST API',
    'GraphQL',
    'WebSockets',
    'Authentication',
    'Authorization',
    'OAuth',
    'JWT',
    'Web Security',
    'CORS',
    'HTTP',
    'HTTPS',
    'SSL/TLS',
    'Responsive Design',
    'Progressive Web Apps',
    'Web Components',
    'DOM',
    'Browser APIs',
    'Web Performance',
    "Django",

    // Database & Storage
    'SQL',
    'NoSQL',
    'MongoDB',
    'PostgreSQL',
    'MySQL',
    'Redis',
    'Database Design',
    'Data Modeling',
    'Indexing',
    'Query Optimization',
    'Transactions',
    'ACID',
    'Caching',
    'Data Migration',
    'Backups',
    'Data Warehousing',

    // DevOps & Infrastructure
    'DevOps',
    'CI/CD',
    'Docker',
    'Kubernetes',
    'Containerization',
    'Microservices',
    'Service Mesh',
    'Cloud Computing',
    'AWS',
    'Azure',
    'Google Cloud',
    'Serverless',
    'Infrastructure as Code',
    'Configuration Management',
    'Monitoring',
    'Logging',
    'System Design',
    'Load Balancing',
    'Scalability',
    'High Availability',

    // Programming Languages
    'Python',
    'Java',
    'C',
    'C++',
    'C#',
    'Ruby',
    'PHP',
    'Go',
    'Rust',
    'Swift',
    'Kotlin',
    'Scala',
    'R',
    'MATLAB',
    'Assembly',
    'Bash',
    'PowerShell',

    // Mobile Development
    'iOS Development',
    'Android Development',
    'React Native',
    'Flutter',
    'Mobile UI/UX',
    'App Store',
    'Google Play',
    'Mobile Security',
    'Push Notifications',
    'Mobile Performance',
    'Mobile Testing',

    // AI & Machine Learning
    'Machine Learning',
    'Deep Learning',
    'Neural Networks',
    'Computer Vision',
    'Natural Language Processing',
    'Reinforcement Learning',
    'Data Mining',
    'Feature Engineering',
    'Model Training',
    'Model Deployment',
    'TensorFlow',
    'PyTorch',
    'Scikit-learn',

    // Security
    'Cyber Security',
    'Encryption',
    'Penetration Testing',
    'Vulnerability Assessment',
    'Network Security',
    'Application Security',
    'Security Protocols',
    'Cryptography',
    'Security Best Practices',
    'Ethical Hacking',

    // Software Architecture
    'Architecture Patterns',
    'Domain-Driven Design',
    'Event-Driven Architecture',
    'Monolithic Architecture',
    'Distributed Systems',
    'API Design',
    'System Integration',
    'Message Queues',
    'Caching Strategies',
    'Data Flow',

    // Development Methodologies
    'Agile',
    'Scrum',
    'Kanban',
    'Waterfall',
    'Lean',
    'XP',
    'Project Management',
    'Team Collaboration',
    'Code Review Process',
    'Documentation Practices',

    // Emerging Technologies
    'Blockchain',
    'IoT',
    'Edge Computing',
    'Quantum Computing',
    'AR/VR',
    '5G',
    'Web3',
    'DeFi',
    'Smart Contracts',
    'Metaverse',

    // Career & Professional Development
    'Career Development',
    'Interview Preparation',
    'Code Challenge',
    'Best Practices',
    'Soft Skills',
    'Technical Writing',
    'Public Speaking',
    'Leadership',
    'Mentoring',
    'Remote Work',

    // Tools & Development Environment
    'IDE',
    'VS Code',
    'IntelliJ',
    'Eclipse',
    'Command Line',
    'Terminal',
    'Development Tools',
    'Productivity Tools',
    'Code Editors',
    'Debugging Tools'
];