# Generated by Django 5.1.2 on 2024-12-12 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('userType', models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('super_user', 'super_user')], default='user', max_length=20)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('interested_topics', models.JSONField(blank=True, default=list)),
                ('known_languages', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('code_snippet', models.TextField()),
                ('language', models.CharField(max_length=200)),
                ('language_id', models.IntegerField(default=71)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer_of_the_question', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Vote',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='django_app.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=200)),
                ('language_id', models.IntegerField(default=-1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('details', models.TextField()),
                ('code_snippet', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ManyToManyField(blank=True, related_name='reported_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='django_app.question'),
        ),
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='django_app.question'),
        ),
        migrations.CreateModel(
            name='Question_Vote',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='django_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
