# Generated by Django 5.1.2 on 2024-10-18 08:16

import django_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('code_snippet', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('code_snippet', models.TextField()),
                ('upvotes', models.IntegerField(default=0)),
                ('comments', models.ManyToManyField(blank=True, related_name='question_comments', to='django_app.comment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('userType', models.CharField(choices=[(django_app.models.UserType['ADMIN'], 'admin'), (django_app.models.UserType['USER'], 'user'), (django_app.models.UserType['SUPER_USER'], 'super_user')], default=django_app.models.UserType['USER'], max_length=20)),
                ('bookmarks', models.JSONField(blank=True, default=list)),
                ('comments', models.ManyToManyField(blank=True, related_name='user_comments', to='django_app.comment')),
                ('questions', models.ManyToManyField(blank=True, related_name='user_questions', to='django_app.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
