# Generated by Django 5.1.2 on 2024-11-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='known_languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
