# Generated by Django 5.1.2 on 2024-12-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('question', 'question'), ('discussion', 'discussion')], default='question', max_length=20),
        ),
    ]
