# Generated by Django 5.1.2 on 2024-10-19 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0002_alter_user_usertype"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="about",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="creationDate",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
