# Generated by Django 5.1.2 on 2024-10-19 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0003_question_about_question_creationdate_question_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="about",
            new_name="language",
        ),
    ]
