# Generated by Django 5.1.2 on 2024-11-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_remove_user_bookmarks_user_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='language',
            field=models.CharField(default='Python', max_length=200),
            preserve_default=False,
        ),
    ]
