# Generated by Django 5.1.2 on 2024-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_rename_about_question_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='language_id',
            field=models.IntegerField(default=71),
        ),
        migrations.AddField(
            model_name='question',
            name='language_id',
            field=models.IntegerField(default=71),
        ),
    ]
