# Generated by Django 5.1.2 on 2024-12-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='language_id',
            field=models.IntegerField(default=-1),
        ),
    ]
