# Generated by Django 5.1.2 on 2024-11-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_annotation'),
    ]

    operations = [
    ]
